---
  - name: Update APT package cache
    apt: update_cache=yes

  - name: Run apt-get upgrade
    apt: upgrade=yes

  - name: Install fail2ban
    apt: pkg=fail2ban state=installed

  - name: Install logwatch
    apt: pkg=logwatch state=installed

  - name: Disallow root SSH access
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
    notify: Restart sshd

  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
    notify: Restart sshd

  - name: Install unattended-upgrades
    apt: pkg=unattended-upgrades state=installed

  - name: Adjust APT update intervals
    copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic

  - name: Make sure unattended-upgrades only installs from $ubuntu_release-security
    lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent

  - name: Set up Postfix to relay mail
    debconf: name=postfix
             question='{{ item.question }}'
             value='{{ item.value }}'
             vtype='{{ item.vtype }}'
    with_items:
      - { question: 'postfix/mailname', value: '{{ ansible_fqdn }}', vtype: 'string' }
      - { question: 'postfix/main_mailer_type', value: 'Internet Site', vtype: 'string' }

  - name: Install Postfix
    apt: package={{ item }} state=installed force=yes update_cache=yes cache_valid_time=3600
    with_items:
        - postfix
        - mailutils


  - name: Email log summary daily
    lineinfile: dest=/etc/cron.daily/00logwatch
              regexp="^/usr/sbin/logwatch"
              line="/usr/sbin/logwatch --output mail --mailto {{ logwatch_email }} --detail high"
              state=present create=yes
